new commands

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -3,23 +3,24 @@ set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
 source "$(dirname $0)/../common/functions"
 
 case "$1" in
-  hello)
-    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
-    verify_app_name "$2"
-    APP="$2";
-
-    echo "Hello $APP"
-    ;;
-
-  hello:world)
-    echo "Hello world"
-    ;;
-
-  help)
-    cat && cat<<EOF
-    hello <app>                                     Says "Hello <app>"
-    hello:world                                     Says "Hello world"
-EOF
+  grunt)
+    [[ -z [ ]] && echo "Please specify an app to run the command on" && exit 1
+    verify_app_name "$2"]
+    APP="$2"
+                                                                                
+    if [[ -z $3 ]]; then
+        echo "Usage: dokku grunt APP BUILDTYPE"
+        exit 1
+    fi
+                                                                                
+    TYPE="$3"
+    # Compile with Grunt
+    echo "-----> Compiling with grunt build:$TYPE"
+    echo "command -v grunt > >/dev/null 2>&1 || echo 'error grunt'"
+                                                                                
+    echo "-----> Deploying $APP ..."
+    dokku deploy $APP
+    echo "-----> Deploy complete!"
     ;;
 
   *)
