fixes

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -2,23 +2,10 @@
 set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
 source "$(dirname $0)/../common/functions"
 
-# Check 
-if [[ $1 == grunt]] || [[ $1 == grunt:*]]; then
-    if [[ -z 2 ]]; then
-        echo "You must specify an app name"
-        exit 1
-    else
-        APP=$2
-
-        # Check if app exists with the same name
-        if [! -d "$DOKKU_ROOT/$APP" ]; then
-            echo "App $APP does not exist"
-            exit 1
-        fi
-fi
-
 case "$1" in
   grunt) # build prod or dev
+    [[ -z [ ]] && echo "Please specify an app to run the command on" && exit 1
+    verify_app_name "$2"]
     APP="$2"
 
     if [[ -z $3 ]]; then
@@ -29,8 +16,11 @@ case "$1" in
     TYPE="$3"
     # Compile with Grunt
     echo "-----> Compiling with grunt build:$TYPE"
-    grunt build:$TYPE
-    bind_restart_app $APP
+    echo "command -v grunt > >/dev/null 2>&1 || echo 'error grunt'"
+
+    echo "-----> Deploying $APP ..."
+    dokku deploy $APP
+    echo "-----> Deploy complete!"
     ;;
 
   help)
