fixes

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -16,7 +16,7 @@ case "$1" in
     TYPE="$3"
     # Compile with Grunt
     echo "-----> Compiling with grunt build:$TYPE"
-    command -v grunt > >/dev/null 2>&1 || echo 'error grunt'
+    command -v grunt >/dev/null 2>&1 || echo 'error grunt'
     echo "-----> Deploying $APP ..."
     dokku deploy $APP
     echo "-----> Deploy complete!"
